name = "Krotov"
uuid = "b05dcdc7-62f6-4360-bf2c-0898bba419de"
authors = ["Michael Goerz <mail@michaelgoerz.net> and contributors"]
version = "0.0.1"

[deps]
QuantumControlBase = "f10a33bc-5a64-497c-be7b-6f86b4f0c2aa"
QuantumPropagators = "7bf12567-5742-4b91-a078-644e72a65fc1"

[compat]
QuantumControlBase = "^0.0"
QuantumPropagators = "^0.0"
julia = "1.6"
